### ISSUE TITLE
About memory

### ISSUE THREAD

**Issue by tuji-sjp** [dongyp13/Translation-Invariant-Attacks#4]
How many cards did you use to run this experiment?
And how much memory per card?
Thanks for your answer.

**Comment by tuji-sjp** [comment]
No matter how many cards I use, I still have the following error:

2019-08-12 17:01:05.508069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10203 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:40:00.0, compute capability: 7.5)
INFO:tensorflow:Restoring parameters from inception_v3.ckpt
INFO:tensorflow:Restoring parameters from inception_v4.ckpt
INFO:tensorflow:Restoring parameters from inception_resnet_v2_2016_08_30.ckpt
INFO:tensorflow:Restoring parameters from resnet_v2_152.ckpt
35.9472489357
2019-08-12 17:01:20.245788: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-08-12 17:01:20.453173: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-08-12 17:01:27.849806: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.42GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-08-12 17:01:27.849888: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.42GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
59.1719589233

**Comment by tuji-sjp** [comment]
重新设置了 batch size 好像也不太起作用，不知道是不是 topological sort failed 的问题呢？

**Comment by dongyp13** [comment]
Yes. I only use one GPU. Did you use the correct python and tensorflow versions?

**Comment by tuji-sjp** [comment]
What is the batch size you actually set?  See your source code is 10.
My version is python 2.7 and tensorflow 1.12.0.
Does it have anything to do with cudnn?

**Comment by dongyp13** [comment]
Yes, I set the batch size as 10. I used the cudnn-v7.4. I ran the code on GTX 1080 with 12GB memory.

**Comment by tuji-sjp** [comment]
hello, I encountered another error that I thought was about reading images:
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "attack_iter.py", line 250, in <module>
    tf.app.run()
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py ", line 125, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 230, in main
    for filenames, images in load_images(FLAGS.input_dir, batch_shape):
  File "attack_iter.py", line 90, in load_images
    image = imresize(imread(path, mode='RGB'), [FLAGS.image_height, FLAGS.image_width]).astype(np.float) / 255.0
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 555, in imresize
    im = toimage(arr, mode=mode)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in  newfunc
    return func(*args, **kwds)
  File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 327, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "

ValueError: 'arr' does not have a suitable array shape for any mode.
-----------------------------------------------------------------------------------
Is there a problem with some images?
Whether to modify mode imread(path, mode='RGB')? To mode=None?

**Comment by tuji-sjp** [comment]
hello, I encountered another error that I thought was about reading images:

Traceback (most recent call last):
 File "attack_iter.py", line 250, in 
 tf.app.run()
 File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py ", line 125, in run
 _sys.exit(main(argv))
 File "attack_iter.py", line 230, in main
 for filenames, images in load_images(FLAGS.input_dir, batch_shape):
 File "attack_iter.py", line 90, in load_images
 image = imresize(imread(path, mode='RGB'), [FLAGS.image_height, FLAGS.image_width]).astype(np.float) / 255.0
 File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
 return func(*args, **kwds)
 File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 555, in imresize
 im = toimage(arr, mode=mode)
 File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
 return func(*args, **kwds)
 File "/home/jinping/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 327, in toimage
 raise ValueError("'arr' does not have a suitable array shape for "

ValueError: 'arr' does not have a suitable array shape for any mode.
---------------------------------------------------
Is there a problem with some images?
 Whether to modify ''imread(path, mode='RGB')'' ?  To mode=None?

**Comment by dongyp13** [comment]
You can have a try. Or you can find the image that failed and check whether it was corrupted.

**Comment by tuji-sjp** [comment]
> 
> 
> You can have a try. Or you can find the image that failed and check whether it was corrupted.

OK，I have solved this problem not long ago and just skipped the wrong images. Thank you very much.
